services:
  worker:
    build:
      context: ../../../app
      dockerfile: Dockerfile

    # max tasks is 1 to avoid dissect memleak related to tar container processing
    command: taskiq worker broker:broker tasks --workers ${WORKERS} --max-async-tasks 1 --max-tasks-per-child 1 --ack-type when_received --max-prefetch 1
    volumes:
      - ${TARGETS_DIRECTORY}:/targets
    environment:
      - BACKEND_POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/gflow_db
      - REDIS_URL=${REDIS_URL}
      - EVENT_BROKER_HOST=${EVENT_BROKER_HOST}
      - EVENT_BROKER_PORT=${EVENT_BROKER_PORT}
