services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gflow_db
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d gflow_db" ]
      interval: 5s
      timeout: 5s
      retries: 3

  api:
    build:
      context: ../../../app
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ${TARGETS_DIRECTORY}:/targets
    ports:
      - "8000:8000"
    environment:
      - API_DB_POSTGRES_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/gflow_db
      - BACKEND_POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/gflow_db
      - REDIS_URL=${REDIS_URL}
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_PORT=${OPENSEARCH_PORT}
