input {
    tcp {
        port => 5044
        host => "0.0.0.0"
        codec => "json_lines"
    }
}

filter {
  # Remove Logstash fields and add timeline identifiers
  mutate {
    remove_field => ["[event][original]", "[log][file][path]", "@timestamp", "@version", "[host][name]"]
    remove_field => ["[event]", "[log]", "[host]"]
  }



  ################################################################################
  # Dissect records + Timesketch fields
  ################################################################################

  # Drop recorddescriptor records
  if [_type] and [_data] {
    drop {}
  }

  date {
    match => ["ts", "ISO8601"]
    target => "@timestamp"
    timezone => "UTC"
  }


  # Use Dissect record name as data_type
  mutate {
    replace => {"data_type" => "%{[_recorddescriptor][0]}"}
    gsub => ["data_type", "/", ":"]
  }

  # Remove Dissect metadata fields
  mutate {
    remove_field => ["_classification", "_generated", "_version", "_type", "_recorddescriptor", "_source"]
  }
}


output {
  opensearch {
    action => "index"
    hosts => ["http://opensearch:9200"]
    ssl => false
    index => "%{[evidence_uid]}"
    manage_template => false
    ecs_compatibility => "disabled" 
  }
}
